/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio1;
import java.util.Scanner;
public class App {


    public static void main(String[] args) {
    Scanner sc = new Scanner(System.in);
    
    
    Calculadora calcular = new Calculadora();
    
    int escolha;
    System.out.println("Escolha entre : 1 para soma, 2 para subtracao, 3 para multiplicacao e 4 para divisao");
    escolha = sc.nextInt();
    
    switch(escolha){
        case 1 :
            calcular.Soma();
            break;
        case 2 :
            calcular.Subtracao();
            break;
        case 3 :
            calcular.Multiplicacao();
            break;
        case 4 :
            calcular.Divisao();
            break;
        default:
            System.out.println("Número incorreto");
            break;
    }
       
    
    
    
    
    
    
    }
}
