/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuProjetoJava;
import java.util.Scanner;

public class App {
    
   /* public void promocao(Produto prod){
        System.out.println("O produto " + prod.getNome() + " esta em promoção por apenas " + prod.getPreco());
    }*/

    public static void main(String[] args) {
        
        Scanner sc = new Scanner(System.in);
        /*
        int numero1, numero2;
        
        
        System.out.println("Digite um número: ");
        numero1 = sc.nextInt();
        
        System.out.println("Digite outro número: ");
        numero2 = sc.nextInt();
        
        System.out.println("Resultado " + (numero1 + numero2));
        
        */
        
        String nome,sobrenome;
        int idade;
        
        System.out.println("Qual o seu nome?");
        nome = sc.nextLine();
        
        System.out.println("Qual a sua idade?");
        idade = sc.nextInt();
        sc.nextLine();
        
        System.out.println("Qual o seu sobrenome?");
        sobrenome = sc.nextLine();
        

        
        System.out.println("Ola " + nome + " " + sobrenome + "!, Você tem " + idade + " anos.");
        sc.close();
       
       /* 
        TesteJava meuTeste = new TesteJava();
        meuTeste.somar(9, 9);
        */
        /*
        int idade = 12; //Número inteiro
        double altura = 1.70 ; //Número que podem ter casa decimal
        String nome = "Pedro" ; //Textos e quaisquer números de caracteres
        char inicial = 'P' ; //Semelhante a string, mas com unico caracter
        boolean souEstudante = true ; //Verdadeiro ou falso
*/
        /*
        int numero = 5;
        if(numero > 0){
            System.out.println("Número negativo");
        }else{
            System.out.println("Número positivo");
        }

*/
        /*
        int diasDaSemana = 7;
        
        switch(diasDaSemana){
            case 1 :
                    System.out.println("Segunda");
                    break;
            case 2 :
                    System.out.println("Terça");
                    break; 
            case 3 :
                    System.out.println("Quarta");
                    break;
            case 4 :
                    System.out.println("Quinta");
                    break;
            case 5 :
                    System.out.println("Sexta");
                    break;            
            case 6 :
                    System.out.println("Sabado");
                    break;            
            case 7 :
                    System.out.println("Domingo");
                    break;
                    
            
        }*/
        
        /*int numero = 9;
                
                if(numero % 2 == 0){
                    System.out.println("Par");
                }else{
                    System.out.println("Impar");
                }
                
                String resultado = (numero % 2 == 0)? "Par" : "Impar";
                System.out.println("O número é " + resultado);/*
        
        */
        
        /*int voltas = 0;
        
        while(voltas < 10){
            System.out.println("Pedale,você ja deu " + voltas + " Voltas");
            voltas ++;
        }
        System.out.println("Você chegou ao final");
        
        for(int i = 0; i <= 10; i++){
        System.out.println(i);
        }*/
        
        /*Pessoa novaPessoa = new Pessoa("Joao",25);
        novaPessoa.caminhar();*/
        /*
        Produto novoProd = new Produto("Livro",55.99);
        System.out.println(novoProd.getNome());
        
        Eletronico novoElet = new Eletronico("TV",2999.99,220);
                System.out.println(novoElet.getNome());
                System.out.println(novoElet.getPreco());
                System.out.println(novoElet.getTensao());
                
                
                App meuApp = new App();
                meuApp.promocao(novoElet);
*/
        
        
    }
                
}
    

