/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuSegundoProjetoJava;

// Importa a classe Scanner para permitir a entrada de dados do usuário
import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        // Cria um objeto Scanner para ler a entrada do usuário
        Scanner sc = new Scanner(System.in);
        
        
        
        
        /*
        // Declara duas variáveis inteiras para armazenar os números digitados pelo usuário
        int numero1, numero2;
        
        String nome;
        
        

         // Solicita ao usuário que digite o primeiro número
        System.out.println("Digite um número: ");
        numero1 = sc.nextInt(); // Lê o próximo inteiro digitado pelo usuário e o armazena em numero1
        
        sc.nextLine();
        System.out.println("Digite seu nome: ");
        nome = sc.nextLine();
        
        // Solicita ao usuário que digite o segundo número
        System.out.println("Digite outro número: ");
        numero2 = sc.nextInt(); // Lê o próximo inteiro digitado pelo usuário e o armazena em numero2
        
        System.out.println(nome + ", O resultado é " + (numero1 + numero2));
        */
        /*Frase minhafrase = new Frase();
        minhafrase.imprimiFrase();*/
        
        /*Veiculo meuVeiculo = new Veiculo(4,"Citroen",2000);
        meuVeiculo.andar();
        
        Carro meuCarro = new Carro("Ferrari",3000,2);
        meuCarro.andar();
        meuCarro.getMarca();
        meuCarro.cavalinhoDePau();
        */
        
    }
}
